use_frameworks!

platform :ios, '8.0'

target 'YUTableLayoutView_Example' do
  pod 'YUTableLayoutView', :path => '../'

  target 'YUTableLayoutView_Tests' do
    inherit! :search_paths

    
  end
end
