source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Yanyuxxxx/YURepo.git'

use_frameworks!
platform :ios, '8.0'

plugin 'cocoapods-bin'
use_binaries!

set_use_source_pods ['YUTableLayoutView']

#use_binaries_with_spec_selector! do |spec|
#  spec.name == 'YUTableLayoutView'
#end

target 'YUTableLayoutView_Example' do

  pod 'YUTableLayoutView', :path => '../'
#  pod 'YUTableLayoutView', '0.0.8'

end
